apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-complianceoperator
  namespace: policies
placementRef:
  name: placement-policy-complianceoperator
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: policy-complianceoperator
    kind: Policy
    apiGroup: policy.open-cluster-management.io
