apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cicd-tools

# Deploy pre-configured SonarQube and Nexus from Red Hat Canada demo catalog.
bases:
  - github.com/redhat-cop/gitops-catalog/nexus2/base?ref=main
  - ../../../library/sonarqube8/overlays/plugins

resources:
  - namespace.yaml